import turtle
import random
turtle.tracer(0, 0)
turtle.up()
turtle.goto(175, 125)
turtle.down()
turtle.pencolor("white")
turtle.fillcolor("#ffffff")
turtle.begin_fill()
turtle.right(180)
turtle.circle(50, -360)
turtle.end_fill()
turtle.pencolor("#000000")
turtle.fillcolor("#000000")
turtle.up()
turtle.goto(125, 125)
turtle.down()
turtle.right(180)
turtle.begin_fill()
turtle.right(180)
turtle.circle(50, -360)
turtle.end_fill()
def create_star(top_x, top_y, bottom_x, bottom_y, color, count):
  for i in range(count):
    x = random.uniform(top_x, bottom_x)
    y = random.uniform(top_y, bottom_y)
    turtle.up()
    turtle.goto(x, y)
    turtle.down()
    turtle.fillcolor(color)
    turtle.begin_fill()
    for i in range(5):
      turtle.forward(20)
      turtle.right(144)
    turtle.end_fill()
    turtle.forward(10)
    turtle.begin_fill()
    turtle.right(180)
    turtle.circle(4, -360)
    turtle.end_fill()
turtle.bgcolor("#000000")
turtle.speed(1000)
turtle.pencolor("yellow")
create_star(-250, 200, 150, -150, "#f2ff00", 40)
create_star(250, 0, 150, -150, "#f2ff00", 10)
turtle.update()